# The URL the site will be built for
base_url = "https://example.com"

# site title and description; used in feeds
title = "a n title"
description = "a n description"

# override output dir
# output_dir = "public"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# minify html, default to false
minify_html = true

# glob patterns for asset to ignore when process content dir, defaults to none, == all assets copied to public
# ignored_content = [] # ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]

# generate feed default false
generate_feed = true

# filename for feed, used as template filename also, default atom.xml atom 1.0, rss.xml render RSS 2.0 feed
# must match template?
feed_filename = "atom.xml"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# feed limit
#feed_limit = 20

# hard_link_static = false

theme = "terminimal"

taxonomies = [
    {name = "tags", lang = "en", rss = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# theme
highlight_theme = "boron"

[extra]
# Put all your custom variables here

# terminimal theme accent color, one of: blue, green, orange, pink, red, defaults to blue. 
accent_color = "orange"
# terminimal theme background color, one of: blue, dark, green, orange, pink, red, defaults to accent color, not specified, to blue
background_color = "dark"
# Enabling dark background will also modify primary font color to be darker.

# terminimal theme logo text - defaults to "Terminimal theme"
logo_text = "My blog"
# terminimal theme logo link - defaults to base_url.
logo_home_link = "/take/me/away!"

# terminimal theme author name: when specified, modifies the default copyright text. Apart from author, it will contain current year and a link to the theme.
author = "A N"

# terminimal theme copyright text in HTML format. If specified entirely replaces default copyright and author.
copyright_html = "My custom&nbsp;<b>copyright</b>"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration

    { name = "Home", url = "$BASE_URL/" },

    { name = "Projects", url = "$BASE_URL/projects/" },

    { name = "Blog", url = "$BASE_URL/blog/" },
    #{name = "blog", url = "$BASE_URL"},
    #{name = "archive", url = "$BASE_URL/archive"},

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    #{ name = "tags", url = "$BASE_URL/tags"},
    { name = "Tags", url = "$BASE_URL/tags/" },

    { name = "Causes", url = "$BASE_URL/causes/" },
    { name = "Contact/About me", url = "$BASE_URL/about" },

    # set newtab to true to make the link open in new tab
    { name = "github", url = "https://github.com/aniewoehner", newtab = true},

    # other
    { name = "NWS weather", url = "https://weather.gov", newtab = true},
]

# terminimal theme -- did not set up pagination

# terminimal theme set HTML language, also zola not just theme
default_language = "en"

# terminimal theme - enable full unicode, not just subset, defaults to false
use_full_hack_font = true

# terminimal theme - favicon URL, should point to file located in site 'static' directory
favicon = "/favicon-32x32.png"
# terminimal theme - favicon mimetype, defaults to "image/x-icon"
favicon_mimetype = "image/png"

# terminimal pagination
# show links to earlier and later posts on each post page, default to true
enable_post_view_navigation = true
# text shown at bottom of post, before earlier/later links, defaults to thanks for reading read other posts
#post_view_navigation_prompt = "Read more"

# external links open in new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
#external_links_target_blank = false

# Whether to set rel="nofollow" for all external links
#external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
#external_links_no_referrer = false

smart_punctuation = false

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100

# Optional translation object for the default language
# Example:
#     default_language = "fr"
#
#     [translations]
#     title = "Un titre"
#

